import {describe, it, expect, beforeEach, afterEach} from 'vitest';
import {rm, access} from 'node:fs/promises';
import {join} from 'node:path';
import {generateFiles, formatFiles} from '../src/generate.js';

const OUTPUT_DIR = join(process.cwd(), 'tests', '.tmp-dry-run');

describe('--dry-run (generateFiles + formatFiles)', () => {
  beforeEach(async () => {
    await rm(OUTPUT_DIR, {recursive: true, force: true});
  });

  afterEach(async () => {
    await rm(OUTPUT_DIR, {recursive: true, force: true});
  });

  it('produces a non-empty file map without touching disk', async () => {
    const files = await generateFiles({
      input: 'examples/openapi.json',
      output: OUTPUT_DIR,
      clean: true,
      groupBy: 'tag',
    });

    expect(Object.keys(files).length).toBeGreaterThan(0);
    expect(files['index.ts']).toBeDefined();
    expect(files['resources/users.api.ts']).toBeDefined();

    // Output directory must not be created by generateFiles.
    await expect(access(OUTPUT_DIR)).rejects.toThrow();
  });

  it('formatFiles adds the auto-generated header and formats', async () => {
    const files = await generateFiles({
      input: 'examples/openapi.json',
      output: OUTPUT_DIR,
      clean: true,
      groupBy: 'tag',
    });
    const formatted = await formatFiles(files);

    const indexContent = formatted['index.ts'];

    expect(indexContent).toContain('// Auto-generated by ng-openapi-signals.');
    expect(indexContent).toContain('// Do not edit manually.');
  });

  it('formatFiles output is stable (idempotent)', async () => {
    const files = await generateFiles({
      input: 'examples/openapi.json',
      output: OUTPUT_DIR,
      clean: true,
      groupBy: 'tag',
    });
    const once = await formatFiles(files);
    const twice = await formatFiles(once);

    expect(twice).toEqual(once);
  });
});