import {describe, it, expect, beforeEach, afterEach} from 'vitest';
import {rm, readdir, readFile, access} from 'node:fs/promises';
import {join} from 'node:path';
import {generate} from '../src/generate.js';

const FIXTURES_DIR = join(process.cwd(), 'tests', 'fixtures');
const OUTPUT_DIR = join(process.cwd(), 'tests', '.tmp-fixtures');

/**
 * Dynamically discover all fixture files so that new fixtures added to
 * `tests/fixtures/` are automatically covered without modifying this test.
 */
async function listFixtures(): Promise<string[]> {
  const entries = await readdir(FIXTURES_DIR);
  return entries
    .filter((f) => f.endsWith('.yml') || f.endsWith('.yaml'))
    .map((f) => join(FIXTURES_DIR, f));
}

/** Recursively lists all `.ts` files under `dir` as paths relative to `dir`. */
async function listTsFiles(dir: string, prefix = ''): Promise<string[]> {
  const entries = await readdir(dir, {withFileTypes: true});
  const files: string[] = [];

  for (const entry of entries) {
    const fullPath = join(dir, entry.name);
    const relPath = prefix ? `${prefix}/${entry.name}` : entry.name;

    if (entry.isDirectory()) {
      const nested = await listTsFiles(fullPath, relPath);
      files.push(...nested);
    } else if (entry.name.endsWith('.ts')) {
      files.push(relPath);
    }
  }

  return files;
}

const fixtures = await listFixtures();

describe('fixture-based generator output structure', () => {
  afterEach(async () => {
    await rm(OUTPUT_DIR, {recursive: true, force: true});
  });

  it('discovers at least one fixture', () => {
    expect(fixtures.length).toBeGreaterThan(0);
  });

  for (const fixture of fixtures) {
    const fixtureName = fixture.split(/[\\/]/).pop()!;

    describe(`fixture: ${fixtureName}`, () => {
      beforeEach(async () => {
        await rm(OUTPUT_DIR, {recursive: true, force: true});
        await generate({
          input: fixture,
          output: OUTPUT_DIR,
          clean: true,
          groupBy: 'tag',
        });
      });

      it('generates core runtime files', async () => {
        const expectedCoreFiles = [
          'providers.ts',
          'api-error.ts',
          'api-fetch-client.ts',
          'signal-utils.ts',
          'index.ts',
        ];

        for (const file of expectedCoreFiles) {
          await expect(access(join(OUTPUT_DIR, file))).resolves.toBeUndefined();
        }
      });

      it('generates models/index.ts and resources/index.ts', async () => {
        await expect(access(join(OUTPUT_DIR, 'models', 'index.ts'))).resolves.toBeUndefined();
        await expect(access(join(OUTPUT_DIR, 'resources', 'index.ts'))).resolves.toBeUndefined();
      });

      it('includes the auto-generated header in every generated .ts file', async () => {
        const tsFiles = await listTsFiles(OUTPUT_DIR);

        expect(tsFiles.length).toBeGreaterThan(0);

        for (const relPath of tsFiles) {
          const content = await readFile(join(OUTPUT_DIR, relPath), 'utf8');
          expect(content).toContain('// Auto-generated by ng-openapi-signals.');
          expect(content).toContain('// Do not edit manually.');
        }
      });

      it('re-exports all model modules from models/index.ts', async () => {
        const indexContent = await readFile(join(OUTPUT_DIR, 'models', 'index.ts'), 'utf8');
        const modelFiles = (await listTsFiles(join(OUTPUT_DIR, 'models')))
          .filter((f) => f !== 'index.ts')
          .map((f) => f.replace(/\.ts$/, ''));

        for (const model of modelFiles) {
          expect(indexContent).toContain(`export * from './${model}';`);
        }
      });

      it('re-exports all resource modules from resources/index.ts', async () => {
        const indexContent = await readFile(join(OUTPUT_DIR, 'resources', 'index.ts'), 'utf8');
        const resourceFiles = (await listTsFiles(join(OUTPUT_DIR, 'resources')))
          .filter((f) => f !== 'index.ts')
          .map((f) => f.replace(/\.ts$/, ''));

        for (const resource of resourceFiles) {
          expect(indexContent).toContain(`export * from './${resource}';`);
        }
      });
    });
  }
});
