import {describe, it, expect, beforeEach, afterEach} from 'vitest';
import {rm, readFile, access, writeFile, mkdir} from 'node:fs/promises';
import {join} from 'node:path';
import {generate} from '../src/generate.js';

const OUTPUT_DIR = join(process.cwd(), 'tests', '.tmp-generate');

describe('generate', () => {
  beforeEach(async () => {
    await rm(OUTPUT_DIR, {recursive: true, force: true});
  });

  afterEach(async () => {
    await rm(OUTPUT_DIR, {recursive: true, force: true});
  });

  it('generates all expected files from the example spec', async () => {
    await generate({
      input: 'examples/openapi.json',
      output: OUTPUT_DIR,
      clean: true,
      apiBaseUrlToken: 'API_BASE_URL',
      groupBy: 'tag',
    });

    const expectedFiles = [
      'tokens.ts',
      'api-error.ts',
      'api-fetch-client.ts',
      'signal-utils.ts',
      'index.ts',
      'models/index.ts',
      'models/user.ts',
      'models/create-user-request.ts',
      'resources/index.ts',
      'resources/users.api.ts',
    ];

    for (const file of expectedFiles) {
      await expect(access(join(OUTPUT_DIR, file))).resolves.toBeUndefined();
    }
  });

  it('includes the auto-generated header in every file', async () => {
    await generate({
      input: 'examples/openapi.json',
      output: OUTPUT_DIR,
      clean: true,
      apiBaseUrlToken: 'API_BASE_URL',
      groupBy: 'tag',
    });

    const content = await readFile(join(OUTPUT_DIR, 'resources', 'users.api.ts'), 'utf8');
    expect(content).toContain('// Auto-generated by ng-openapi-signals.');
    expect(content).toContain('// Do not edit manually.');
  });

  it('preserves existing files when clean is false', async () => {
    await mkdir(join(OUTPUT_DIR, 'subdir'), {recursive: true});
    await writeFile(join(OUTPUT_DIR, 'preserved.txt'), 'keep me', 'utf8');

    await generate({
      input: 'examples/openapi.json',
      output: OUTPUT_DIR,
      clean: false,
      apiBaseUrlToken: 'API_BASE_URL',
      groupBy: 'tag',
    });

    const content = await readFile(join(OUTPUT_DIR, 'preserved.txt'), 'utf8');
    expect(content).toBe('keep me');
  });

  it('uses custom API base URL token name', async () => {
    await generate({
      input: 'examples/openapi.json',
      output: OUTPUT_DIR,
      clean: true,
      apiBaseUrlToken: 'CUSTOM_API_URL',
      groupBy: 'tag',
    });

    const tokensContent = await readFile(join(OUTPUT_DIR, 'tokens.ts'), 'utf8');
    expect(tokensContent).toContain('export const CUSTOM_API_URL');

    const clientContent = await readFile(join(OUTPUT_DIR, 'api-fetch-client.ts'), 'utf8');
    expect(clientContent).toContain("import { CUSTOM_API_URL } from './tokens'");
    expect(clientContent).toContain('inject(CUSTOM_API_URL)');
  });

  it('groups by path when groupBy is path', async () => {
    await generate({
      input: 'examples/openapi.json',
      output: OUTPUT_DIR,
      clean: true,
      apiBaseUrlToken: 'API_BASE_URL',
      groupBy: 'path',
    });

    // All example endpoints are under /users, so the file should be users.api.ts
    const content = await readFile(join(OUTPUT_DIR, 'resources', 'users.api.ts'), 'utf8');
    expect(content).toContain('export class UsersApi');
  });
});