import {describe, it, expect, beforeEach, afterEach} from 'vitest';
import {rm, readFile, access} from 'node:fs/promises';
import {join} from 'node:path';
import {generate} from '../src/generate.js';

const OUTPUT_DIR = join(process.cwd(), 'tests', '.tmp-generate');

describe('generate', () => {
  beforeEach(async () => {
    await rm(OUTPUT_DIR, {recursive: true, force: true});
  });

  afterEach(async () => {
    await rm(OUTPUT_DIR, {recursive: true, force: true});
  });

  it('generates all expected files from the example spec', async () => {
    await generate({
      input: 'examples/openapi.json',
      output: OUTPUT_DIR,
    });

    const expectedFiles = [
      'tokens.ts',
      'api-error.ts',
      'api-fetch-client.ts',
      'signal-utils.ts',
      'index.ts',
      'models/index.ts',
      'models/user.ts',
      'models/create-user-request.ts',
      'resources/index.ts',
      'resources/users.api.ts',
    ];

    for (const file of expectedFiles) {
      await expect(access(join(OUTPUT_DIR, file))).resolves.toBeUndefined();
    }
  });

  it('includes the auto-generated header in every file', async () => {
    await generate({
      input: 'examples/openapi.json',
      output: OUTPUT_DIR,
    });

    const content = await readFile(join(OUTPUT_DIR, 'resources', 'users.api.ts'), 'utf8');
    expect(content).toContain('// Auto-generated by ng-openapi-signals.');
    expect(content).toContain('// Do not edit manually.');
  });
});