import {mkdir, rm, writeFile} from 'node:fs/promises';
import {dirname, join} from 'node:path';
import {format} from 'prettier';
import {loadOpenApi} from './openapi';
import type {GeneratorConfig, RuntimeConfig} from './codegen/types';
import {extractSchemas, generateModelFiles} from './codegen/generate-models';
import {extractOperations, generateApiFiles} from './codegen/generate-api';
import {generateRuntimeFiles} from './codegen/generate-runtime';
import {hoistInlineSchemas} from './codegen/inline-schemas';

const DEFAULT_RUNTIME_CONFIG: RuntimeConfig = {
  transport: 'fetch',
  defaultHeaders: {},
  responseTypeHints: true,
};

/** Ensures `config.runtime` is present, defaulting missing fields. */
function withRuntimeDefaults(config: GeneratorConfig): GeneratorConfig {
  const runtime = config.runtime ?? DEFAULT_RUNTIME_CONFIG;
  return {
    ...config,
    runtime: {
      ...runtime,
      transport: runtime.transport ?? 'fetch',
      defaultHeaders: runtime.defaultHeaders ?? {},
      responseTypeHints: runtime.responseTypeHints ?? true,
    },
  };
}

/**
 * Generates the raw (unformatted) file map for the given config.
 *
 * Pure core: loads the OpenAPI document, hoists inline schemas and extracts
 * models/operations, returning a `Record<relativePath, unformattedContent>`.
 * Performs no disk I/O and no Prettier formatting. This is the shared base
 * used by `generate()`, `--dry-run` and `--check`.
 */
export async function generateFiles(
  config: GeneratorConfig,
): Promise<Record<string, string>> {
  const normalizedConfig = withRuntimeDefaults(config);
  const api = await loadOpenApi(normalizedConfig.input);

  // Hoist anonymous inline schemas into components.schemas before extraction.
  hoistInlineSchemas(api);

  const schemas = extractSchemas(api);
  const operations = extractOperations(api);

  return {
    ...generateRuntimeFiles(normalizedConfig),
    ...generateModelFiles(schemas),
    ...generateApiFiles(operations, normalizedConfig),
    'index.ts': generateIndexFile(normalizedConfig),
  };
}

/**
 * Formats every generated file with Prettier and prepends the
 * auto-generated header. Pure function — no disk I/O.
 */
export async function formatFiles(
  files: Record<string, string>,
): Promise<Record<string, string>> {
  const formatted: Record<string, string> = {};

  for (const [fileName, content] of Object.entries(files)) {
    formatted[fileName] = await format(withHeader(content), {
      parser: 'typescript',
      singleQuote: true,
      trailingComma: 'none',
    });
  }

  return formatted;
}

/**
 * Writes the given (formatted) file map to the output directory.
 *
 * When `clean` is `true`, the output directory is removed first. Creates
 * parent directories as needed.
 */
export async function writeFiles(
  output: string,
  files: Record<string, string>,
  clean: boolean,
): Promise<void> {
  if (clean) {
    await rm(output, {
      recursive: true,
      force: true,
    });
  }

  await mkdir(output, {
    recursive: true,
  });

  for (const [fileName, content] of Object.entries(files)) {
    const outputPath = join(output, fileName);

    await mkdir(dirname(outputPath), {
      recursive: true,
    });

    await writeFile(outputPath, content, 'utf8');
  }
}

/**
 * Generates the Angular API client from an OpenAPI specification.
 *
 * Thin wrapper around {@link generateFiles}, {@link formatFiles} and
 * {@link writeFiles}. Behaves identically to previous versions.
 */
export async function generate(config: GeneratorConfig): Promise<void> {
  const files = await generateFiles(config);
  const formatted = await formatFiles(files);
  await writeFiles(config.output, formatted, config.clean);
}

function generateIndexFile(config: GeneratorConfig): string {
  const transport = config.runtime?.transport ?? 'fetch';
  const signalMutations = config.runtime?.signalMutations === true;
  const dateTransformer = config.runtime?.dateTransformer === true;
  const clientExport =
    transport === 'httpClient'
      ? "export * from './api-http-client';"
      : "export * from './api-fetch-client';";
  const mutationExport = signalMutations
    ? "export * from './mutation-utils';\n"
    : '';
  const dateUtilsExport = dateTransformer
    ? "export * from './date-utils';\n"
    : '';

  return `export * from './providers';
export * from './api-error';
${clientExport}
export * from './signal-utils';
${mutationExport}${dateUtilsExport}export * from './models';
export * from './resources';
`;
}

function withHeader(content: string): string {
  const header = `// Auto-generated by ng-openapi-signals.
// Do not edit manually.`;

  // Idempotent: do not add the header twice if the content already has it.
  if (content.startsWith('// Auto-generated by ng-openapi-signals.')) {
    return content;
  }

  return `${header}

${content}`;
}
