import {mkdir, rm, writeFile} from 'node:fs/promises';
import {dirname, join} from 'node:path';
import {format} from 'prettier';
import {loadOpenApi} from './openapi';
import type {GeneratorConfig, RuntimeConfig} from './codegen/types';
import {extractSchemas, generateModelFiles} from './codegen/generate-models';
import {extractOperations, generateApiFiles} from './codegen/generate-api';
import {generateRuntimeFiles} from './codegen/generate-runtime';
import {hoistInlineSchemas} from './codegen/inline-schemas';

const DEFAULT_RUNTIME_CONFIG: RuntimeConfig = {
  transport: 'fetch',
  defaultHeaders: {},
  responseTypeHints: true,
};

/** Ensures `config.runtime` is present, defaulting missing fields. */
function withRuntimeDefaults(config: GeneratorConfig): GeneratorConfig {
  const runtime = config.runtime ?? DEFAULT_RUNTIME_CONFIG;
  return {
    ...config,
    runtime: {
      transport: runtime.transport ?? 'fetch',
      defaultHeaders: runtime.defaultHeaders ?? {},
      responseTypeHints: runtime.responseTypeHints ?? true,
    },
  };
}

export async function generate(config: GeneratorConfig): Promise<void> {
  const normalizedConfig = withRuntimeDefaults(config);
  const api = await loadOpenApi(normalizedConfig.input);

  // Hoist anonymous inline schemas into components.schemas before extraction.
  hoistInlineSchemas(api);

  if (normalizedConfig.clean) {
    await rm(normalizedConfig.output, {
      recursive: true,
      force: true,
    });
  }

  await mkdir(normalizedConfig.output, {
    recursive: true,
  });

  const schemas = extractSchemas(api);
  const operations = extractOperations(api);

  const files: Record<string, string> = {
    ...generateRuntimeFiles(normalizedConfig),
    ...generateModelFiles(schemas),
    ...generateApiFiles(operations, normalizedConfig),
    'index.ts': generateIndexFile(normalizedConfig),
  };

  for (const [fileName, content] of Object.entries(files)) {
    const outputPath = join(normalizedConfig.output, fileName);
    const formatted = await format(withHeader(content), {
      parser: 'typescript',
      singleQuote: true,
      trailingComma: 'none',
    });

    await mkdir(dirname(outputPath), {
      recursive: true,
    });

    await writeFile(outputPath, formatted, 'utf8');
  }
}

function generateIndexFile(config: GeneratorConfig): string {
  const transport = config.runtime?.transport ?? 'fetch';
  const clientExport =
    transport === 'httpClient'
      ? "export * from './api-http-client';"
      : "export * from './api-fetch-client';";

  return `export * from './providers';
export * from './api-error';
${clientExport}
export * from './signal-utils';
export * from './models';
export * from './resources';
`;
}

function withHeader(content: string): string {
  return `// Auto-generated by ng-openapi-signals.
// Do not edit manually.

${content}`;
}
