import {mkdir, rm, writeFile} from 'node:fs/promises';
import {dirname, join} from 'node:path';
import {format} from 'prettier';
import {loadOpenApi} from './openapi';
import type {GeneratorConfig} from './codegen/types';
import {extractSchemas, generateModelFiles} from './codegen/generate-models';
import {extractOperations, generateApiFiles} from './codegen/generate-api';
import {generateRuntimeFiles} from './codegen/generate-runtime';

export async function generate(config: GeneratorConfig): Promise<void> {
  const api = await loadOpenApi(config.input);

  if (config.clean) {
    await rm(config.output, {
      recursive: true,
      force: true,
    });
  }

  await mkdir(config.output, {
    recursive: true,
  });

  const schemas = extractSchemas(api);
  const operations = extractOperations(api);

  const files: Record<string, string> = {
    ...generateRuntimeFiles(config),
    ...generateModelFiles(schemas),
    ...generateApiFiles(operations, config),
    'index.ts': generateIndexFile(),
  };

  for (const [fileName, content] of Object.entries(files)) {
    const outputPath = join(config.output, fileName);
    const formatted = await format(withHeader(content), {
      parser: 'typescript',
      singleQuote: true,
      trailingComma: 'none',
    });

    await mkdir(dirname(outputPath), {
      recursive: true,
    });

    await writeFile(outputPath, formatted, 'utf8');
  }
}

function generateIndexFile(): string {
  return `export * from './tokens';
export * from './api-error';
export * from './api-fetch-client';
export * from './signal-utils';
export * from './models';
export * from './resources';
`;
}

function withHeader(content: string): string {
  return `// Auto-generated by ng-openapi-signals.
// Do not edit manually.

${content}`;
}
